from typing import Callable, Dict, List, Tuple, Union, Any

from .responses import BaseResponse

ViewFunction = Callable[..., BaseResponse]

def split_by_slash(path: str) -> List[str]: ...
def match_url_vars_type(url_vars: Dict[str, str],
                        type_hints: Dict[str, Any]) -> Tuple[bool, Dict[str, Any]]: ...
def match_path(rule: str, path: str) -> Tuple[bool, Dict[str, str]]: ...

class Router:
    endpoints: Tuple[str, Dict[str, ViewFunction], Dict[str, Any]]
    def __init__(self) -> None: ...
    def match(self, path: str, method: str) -> Tuple[ViewFunction, Dict[str, Any]]: ...
    def add(self, rule: str, method: str, name: str, callback: ViewFunction) -> None: ...
    def reverse(self, name: str, **kwargs: Any) -> str: ...
